spring:
  application:
    name: gateway
  config:
    import: optional:configserver:http://localhost:7999
  cloud:
    config:
      fail-fast: true
  rabbitmq:
    host: localhost
    username: guest
    password: guest