spring:
    application:
        name: config-service
    cloud:
        config:
            server:
                git:
                    uri: ${CLOUD_CONFIG_GIT_URI}
                    password: ${CLOUD_CONFIG_GIT_PASSWORD}
                    default-label: master
                    search-paths: "{application}"

server:
    port: 7999